# Generated by Django 3.2.12 on 2022-05-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchmate_app', '0003_reviews_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='reviews_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
